/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/users": {
    /** List users */
    get: {
      responses: {
        /** @description List of users */
        200: {
          content: {
            "application/json": components["schemas"]["User"][];
          };
        };
      };
    };
    /** Create a user */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateUserInput"];
        };
      };
      responses: {
        /** @description Created user */
        201: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id: number;
      name: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "admin" | "coordinator" | "tutor" | "parent";
      rut?: string | null;
      phone?: string | null;
      address?: string | null;
      chargeEmail?: string | null;
      institutionId?: number | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateUserInput: {
      /** @enum {string} */
      role: "admin" | "coordinator" | "tutor" | "parent";
      name: string;
      /** Format: email */
      email: string;
      rut: string;
      phone?: string;
      address?: string;
      chargeEmail?: string;
      institutionId?: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
